name: Deploy FoodSale to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.0'
          channel: stable

      - name: Instalar dependencias
        run: flutter pub get

      - name: Compilar FoodSale
        run: flutter build web --release --base-href "/FoodSale-Mobile/"

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Preparar aplicación
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Publicar
        uses: actions/deploy-pages@v4
